# общее
name: test_run #'run5_en6_q5'
save_dir: "/home/max/ieos/small_obj/vid_pred/runs/def_detr/"
from_save: ''


# параметры данных
train_dataset_path: "/home/max/ieos/small_obj/vid_pred/data/simple_detr_dataset/train_1_frame_v2"
val_dataset_path: "/home/max/ieos/small_obj/vid_pred/data/simple_detr_dataset/test_1_frame_v2"
mean: [0.5, 0.5, 0.5] #[0.5, 0.5, 0.5, 0.5, 0.5, 0.5,0.5, 0.5, 0.5, 0.5]
std: [0.5, 0.5, 0.5] #[0.5, 0.5, 0.5, 0.5, 0.5, 0.5,0.5, 0.5, 0.5, 0.5]
norm: true
train_batch_size: 8
val_batch_size: 18
mode: 'rgb'
max_bboxes: 5
r_size: [224,224]

# параметры модели
model_type: 'def_endet'
backbone: 'convnext'
num_encoder_blocks: 6
num_decoder_blocks: 12
num_queries: 5
num_cls: 1
emb_dim: 256
img_size: [480, 640]
num_feature_levels: 4

# параметры обучения
epoches: 100
lr: 0.001
tb: true
progress_bar: true

# коэффициенты матчера
cost_class: 1.
cost_bbox: 5.
cost_giou: 2.

# коэффициенты лосса
cls_scale: 2
bbox_scale: 5
giou_scale: 2

# tech
debug: false
start_epoch: 0